<div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>               
            <form action="<?= $router->urlFor('urls.store') ?>" method="post" class="row">
                <div class="col-8">
                    <label for="text" class="visually-hidden">URL для проверки</label>
                    <input type="text" 
                        name="url[name]" 
                        class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>" 
                        placeholder="https://www.example.com"
                        value="<?= isset($urlValue) ? htmlspecialchars($urlValue) : '' ?>">
                        <?php if (isset($errors)): ?>
                            <div class="invalid-feedback">
                                <?= htmlspecialchars(($errors['errorMessage'] ?? '')) ?>
                            </div>
                        <?php endif; ?>
                </div>
                <div class="col-4">
                    <input type="submit" class="btn btn-primary btn-lg w-100 text-uppercase" value="Проверить">
                </div>
            </form>
        </div>
    </div>
</div>
