<?= $this->fetch('header.phtml') ?>

<main class="flex-grow-1">
  <div class="container-lg mt-3">
    <h1>Сайты</h1>
      <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
          <thead>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($urls as $url): ?>
            <tr>
              <td><?= htmlspecialchars($url['id']) ?></td>
              <td>
                <a href="<?= $router->urlFor('urls.show', ['id' => $url['id']]) ?>">
                  <?= htmlspecialchars($url['name']) ?>
                </a>
              </td>
              <td><?= htmlspecialchars($url['created_at']) ?></td>
              <td>-</td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
  </div>
</main>

<?= $this->fetch('footer.phtml') ?>