<?php
// Убедитесь, что переменные $router и $choice доступны
if (!isset($router) || !isset($choice)) {
    // Если переменные не переданы, можно попробовать получить их из глобального контекста
    // или установить значения по умолчанию
    $choice = $choice ?? 'home';
}
?>

<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= $router->urlFor('home') ?>">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link <?= ($choice === 'home' ? 'active' : '') ?>" href="<?= $router->urlFor('home') ?>">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= ($choice === 'urls' ? 'active' : '') ?>" href="<?= $router->urlFor('urls.index') ?>">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>